databases:
  - name: chat_japanese_db
    databaseName: chat_japanese
    user: chat_user
    region: singapore
    plan: free

services:
  - type: web
    name: chat_japanese
    env: python
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn chat_japanese.wsgi --log-file -"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chat_japanese_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4


    autoDeploy: true
